name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk17
          arguments: shadowJar
          gradle-version: wrapper
      - name: Rename and move files to root
        run: |
          mv build/libs/Moonlight-1.8.9-all.jar Moonlight.jar
          mv json/Moonlight.json Moonlight.json
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moonlight
          path: |
            Moonlight.jar
            Moonlight.json
