name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  GRADLE_TASK: shadowJar
  JAR_NAME: Moonlight.jar
  JSON_NAME: Moonlight.json
  BUILD_DIR: build/libs
  JSON_DIR: json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Configure Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Project with Gradle
        run: ./gradlew ${{ env.GRADLE_TASK }} --no-daemon

      - name: Rename and Move Files to Root
        run: |
          mv ${BUILD_DIR}/Moonlight-1.8.9-all.jar ${GITHUB_WORKSPACE}/${JAR_NAME}
          mv ${JSON_DIR}/MoonLight.json ${GITHUB_WORKSPACE}/${JSON_NAME}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moonlight
          path: |
            ${{ env.JAR_NAME }}
            ${{ env.JSON_NAME }}
